# Generated by Django 5.1.3 on 2025-01-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiporders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('ship_date', models.DateField()),
            ],
        ),
    ]
