# Generated by Django 5.1.3 on 2025-01-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiporders', '0002_shiporder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='InventoryCatalog',
        ),
        migrations.DeleteModel(
            name='ShipOrder',
        ),
    ]
