# Generated by Django 5.1.3 on 2024-11-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
    ]
