# Generated by Django 5.1.3 on 2024-11-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20241107_1344'),
    ]

    operations = [
    ]
